export const SET_FRIENDS = "SET_FRIENDS";
export const SET_FRIENDS_FAILED = "SET_FRIENDS_FAILED";
export const UPDATE_FRIENDS = "UPDATE_FRIENDS";

export const SET_GROUPS = "SET_GROUPS";
export const SET_GROUPS_FAILED = "SET_GROUPS_FAILED";
