export const SET_FRIENDS = "SET_FRIENDS";
export const FETCH_FRIENDS_FAILED = "FETCH_FRIENDS_FAILED";

export const SET_GROUPS = "SET_GROUPS";
export const FETCH_GROUPS_FAILED = "FETCH_GROUPS_FAILED";
